"""extend transactions for payments

Revision ID: 00919696cefa
Revises: 91fe078fbaf2
Create Date: 2026-04-29 12:59:05.977080

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '00919696cefa'
down_revision: Union[str, None] = '91fe078fbaf2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('payment_method_id', sa.UUID(), nullable=False))
    op.add_column('transactions', sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('fee_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.add_column('transactions', sa.Column('seller_amount', sa.Numeric(precision=10, scale=2), nullable=False))
    op.create_foreign_key(None, 'transactions', 'payment_methods', ['payment_method_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'seller_amount')
    op.drop_column('transactions', 'fee_amount')
    op.drop_column('transactions', 'amount')
    op.drop_column('transactions', 'payment_method_id')
    # ### end Alembic commands ###
